services:
  postgres:
    image: postgres:17.5
    container_name: streaming-tracker-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
  streaming-tracker:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
