services:
  streamingtracker:
    container_name: streamingtracker
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./db:/app/db
    ports:
      - 127.0.0.1:3000:3000

